{+forward-override{forward-socks5 127.0.0.1:9051 .}}

.google.com/.*youtube\.com.*
.google.com/.*feedburner\.com.*

.blogger.com
.blogspot.com

.appspot.com

.docs.google.com
.encrypted.google.com

.feedburner.com

.youtube.com
.ytimg.com

.rsf.org
.torproject.org
.xys.org

.facebook.com
.fbcdn.net

.twitter.com

.mail-archive.com
