{+forward-override{forward-socks4a 127.0.0.1:9050 .}}
74.125.94.160
72.52.81.22
67.220.91.23
213.251.145.96
67.220.91.18
.0.2.9
.blog.51.ca
.info.51.ca
.bbs.51.ca
.identi.ca
.video.aol.ca
.pastebin.ca
.psiphon.ca
.news.singtao.ca
.forum.yorkbbs.ca
.newnews.ca
.rcinet.ca
.sinonet.ca
.-------------en.WikiPedia-----
.bd.zhe.la
.zuo.la
.bbs2.newsgroup.la
.forum.newsgroup.la
.bbs.newsgroup.la
.fanfou.la
.gfw.org.ua
.ub0.cc
.3b8.cc
.sex8.cc
.s-a.cc
.netme.cc
.wretch.cc
.uni.cc
.newspeak.cc
.hacken.cc
.the-sun.on.cc
.gaymap.cc
.disp.cc
.twistar.cc
.ptt.cc
.nic.cz.cc
.mike.cz.cc
.ifan.cz.cc
.wo.tc
.fredwilson.vc
.hudatoriq.web.id
.ilove80.be
.maruta.be
.yooper.be
.youtu.be
.i2p2.de
.ccc.de
.dolc.de
.dw-world.de
.addictedtocoffee.de
.twibble.de
.deutsche-welle.de
.zhao.jinhai.de
.asianwomensfilm.de
.kaiyuan.de
.prosiben.de
.csuchen.de
.chinesen.de
.fanfou.de
.privacybox.de
.--.google.
.groups.google.
.freewallpaper4.me
.wjd.name
.psblog.name
.kui.name
.tech.blog.aknin.name
.tumblr.fenglu.name
.demonoid.me
.tweeplike.me
.reflectionof.me
.zhufeng.me
.rapidscan.me
.t.leeiio.me
.menro.me
.twip.me
.wp.me
.saiq.me
.blog.thesilentnumber.me
.life.fly4ever.me
.amzs.me
.riku.me
.log.riku.me
.sogrady.me
.9city.me
.ark10.org
.china21.org
.lists.w3.org
.89-64.org
.neverforget8964.org
.cdp1998.org
.webupd8.org
.blog.tatoeba.org
.rfa.org
.ogaoga.org
.twtr2src.ogaoga.org
.guancha.org
.secure.wikimedia.org
.uncyclomedia.org
.zh-yue.wikipedia.org
.zh.wikipedia.org
.en.wikipedia.org
.wikimapia.org
.softpanorama.org
.xiaoma.org
.radiovaticana.org
.h1n1china.org
.greatfirewallofchina.org
.h-china.org
.hrichina.org
.cochina.org
.bestforchina.org
.amnestyusa.org
.xdelta.org
.cuihua.org
.duihua.org
.mininova.org
.citizenlab.org
.docs.latexlab.org
.blog.mongodb.org
.tornadoweb.org
.cdpweb.org
.spiritjb.org
.blog.aegisub.org
.psiphon.civisec.org
.orzistic.org
.greetroc.org
.bjzc.org
.sysresccd.org
.tumblweed.org
.fscked.org
.www.ned.org
.breakingnewsworld.org
.cnd.org
.tibetfund.org
.bigsound.org
.thomasbernhard.org
.popyard.org
.tchrd.org
.blogtd.org
.xpud.org
.wqyd.org
.17e.org
.unknownspace.org
.zh.wikisource.org
.--zh.wikisource.org
.cclife.org
.futuremessage.org
.pastie.org
.blog.google.org
.rfamobile.org
.vcf-online.org
.globalvoicesonline.org
.faststone.org
.hkzone.org
.tynsoe.org
.soundofhope.org
.fillthesquare.org
.peacefire.org
.lookingglasstheatre.org
.pornbase.org
.rsf-chinese.org
.freedomhouse.org
.www.gmote.org
.archive.org
.chinainperspective.org
.m.oulove.org
.sesawe.org
.nidaye.org
.blog.kangye.org
.xizang-zhiye.org
.nobelprize.org
.hkbf.org
.rsf.org
.gdzf.org
.fofg.org
.art.twgg.org
.linuxconfig.org
.shangfang.org
.huanghuagang.org
.blog.golang.org
.wengewang.org
.www.wangruowang.org
.mail.diyang.org
.weijingsheng.org
.zhongmeng.org
.dalianmeng.org
.tiandixing.org
.aircrack-ng.org
.wezhiyong.org
.waikeung.org
.whitebear.freebearblog.org
.emacsblog.org
.twilog.org
.bullog.org
.teachparentstech.org
.laogai.org
.youpai.org
.de-sci.org
.danwei.org
.dowei.org
.icl-fi.org
.yyii.org
.aiyori.org
.minghui.org
.yi.org
.xiaogaozi.org
.cpj.org
.dvorak.org
.linux.fatduck.org
.dphk.org
.hellouk.org
.grandtrial.org
.fourthinternational.org
.python-excel.org
.markmail.org
.tweepml.org
.waveprotocol.org
.sharecool.org
.status.twhirl.org
.seul.org
.chinasoul.org
.srcf.ucam.org
.tacem.org
.internetfreedom.org
.lupm.org
.transgressionism.org
.globalmuseumoncommunism.org
.blog.chromium.org
.dev.chromium.org
.codereview.chromium.org
.www.chromium.org
.futurechinaforum.org
.packages.debian.org
.blog.symbian.org
.zhengjian.org
.rameshsubramanian.org
.renyurenquan.org
.nvquan.org
.leecheukyan.org
.zengjinyan.org
.blog.fdcn.org
.govecn.org
.ncn.org
.uocn.org
.newscn.org
.yogichen.org
.chinesepen.org
.qienkuen.org
.rangzen.org
.blog.gatein.org
.chinayuanmin.org
.jingpin.org
.bfnn.org
.python.org
.trackon.org
.vatn.org
.morningsun.org
.1bao.org
.shizhao.org
.shixiao.org
.wangjinbo.org
.marco.org
.dailytodo.org
.mhradio.org
.hkgreenradio.org
.youthnetradio.org
.ibiblio.org
.asiademo.org
.chandoo.org
.blog.sogoo.org
.peopo.org
.minzhuzhongguo.org
.trialofccp.org
.hqcdp.org
.tldp.org
.cdjp.org
.hkjp.org
.areca-backup.org
.vcfbuilder.org
.collateralmurder.org
.tiananmenmother.org
.iconpaper.org
.www.whatbrowser.org
.data.clementine-player.org
.www.clementine-player.org
.etizer.org
.ccdtr.org
.alasbarricadas.org
.fame.gonzolabs.org
.1984bbs.org
.twbbs.org
.qxbbs.org
.pbs.org
.cuhkacs.org
.hungerstrikeforaids.org
.diaoyuislands.org
.tuxmachines.org
.tibetwrites.org
.pbxes.org
.xysblogs.org
.wikileaks.org
.openleaks.org
.zh.wikibooks.org
.tiantibooks.org
.301works.org
.gardennetworks.org
.ibros.org
.sitemaps.org
.sexyclips.org
.chinaaffairs.org
.ifcss.org
.tibetanyouthcongress.org
.uyghurcongress.org
.android.wordpress.org
.ios.wordpress.org
.chinafreepress.org
.www.wan-press.org
.speedpluss.org
.democrats.org
.chinacomments.org
.shenyunperformingarts.org
.marxists.org
.thelius.org
.aboutus.org
.linuxreviews.org
.bignews.org
.xys.org
.isgreat.org
.blog.webmproject.org
.torproject.org
.digitalnomadsproject.org
.site.icu-project.org
.md-t.org
.www.freetibet.org
.savetibet.org
.xinhuanet.org
.crd-net.org
.yuming.flnet.org
.twiggit.org
.civilhrfront.org
.rss.slashdot.org
.wallornot.org
.blog.openinkpot.org
.vot.org
.skulpt.org
.blog.joeyrobert.org
.asiaharvest.org
.blog.humanrightsfirst.org
.budaedu.org
.tianzhu.org
.shenshou.org
.cdpwu.org
.canyu.org
.post.anyu.org
.blog.iphone-dev.org
.freeciv.org
.chinainterimgov.org
.fgmtv.org
.october-review.org
.leftgamerreview.org
.chinagfw.org
.fuckgfw.org
.hrw.org
.moztw.org
.mondex.org
.avidemux.org
.whyx.org
.thepiratebay.org
.chinaway.org
.journalofdemocracy.org
.www.khanacademy.org
.linuxtoy.org
.recordhistory.org
.chinagreenparty.org
.fireofliberty.org
.amnesty.org
.autoproxy.org
.qvodzy.org
.planetsuzy.org
.gmhz.org
.freeoz.org
.zaobao.com.sg
.wenhui.ch
.mad-ar.ch
.wikileaks.ch
.twa.sh
.wapedia.mobi
.shkspr.mobi
.feedbooks.mobi
.-------------zh.Wiki----------
.jinn.li
.bao.li
.hen.bao.li
.paper.li
.blog.nihilogic.dk
.blog.qooza.hk
.hkjp.easyweb.hk
.catholic.org.hk
.alliance.org.hk
.rthk.org.hk
.-rthk.org.hk
.liberal.org.hk
.oxfam.org.hk
.islam.org.hk
.salvation.org.hk
.sowers.org.hk
.bfsh.hk
.mihk.hk
.fail.hk
.blog.sina.com.hk
.forum.sina.com.hk
.news.sina.com.hk
.google.com.hk
.news.google.com.hk
.myforum.com.hk
.open.com.hk
.xinmiao.com.hk
.yahoo.com.hk
.discuss.com.hk
.hkdailynews.com.hk
.longhair.hk
.hotpot.hk
.civicparty.hk
.rapid.pk
.ezpc.tk
.tamiaode.tk
.webfee.tk
.tkforum.tk
.notebookaddon.tk
.solozorro.tk
.tkit.tk
.igfw.tk
.www.zaurus.org.uk
.myforum.com.uk
.bbc.co.uk
.newsforums.bbc.co.uk
.news.bbc.co.uk
.englishfromengland.co.uk
.geekmade.co.uk
.www.bulbous.freeserve.co.uk
.video.aol.co.uk
.dabr.co.uk
.blog.dabr.co.uk
.hiveminds.co.uk
.barnabu.co.uk
.usmc.mil
.soc.mil
.marines.mil
.308578.html
.download.html
.fuck-beijing-olympics.html
.testtools.china-test.html
.twurl.nl
.twt.tl
.mtw.tl
.blog.kl.am
.xmusic.fm
.index.cfm
.ping.fm
.favstar.fm
.tweetmylast.fm
.tuite.im
.ff.im
.kun.im
.t.kun.im
.cao.im
.fanfou.im
.fanfou\.im
.mk5000.com
.8000.com
.read100.com
.9001700.com
.sf520.com
.dadi360.com
.china101.com
.ck101.com
.mobile01.com
.cn.mobile01.com
.5i01.com
.tap11.com
.sex-11.com
.newspace21.com
.mx981.com
.rapidshare1.com
.gpass1.com
.dev102.com
.fc2.com
.labyrinth2.com
.freeman2.com
.porn2.com
.dtiserv2.com
.basetimesheightdividedby2.com
.881903.com
.www.wet123.com
.makzhou.warehouse333.com
.code1984.com
.topstyle4.com
.bythehost15.com
.blog.s135.com
.t35.com
.iu45.com
.bet365.com
.bt95.com
.blambin.byethost16.com
.wg1966.com
.blog.syx86.com
.cubicle17.com
.tokyo-247.com
.plus28.com
.hk32168.com
.state168.com
.adult168.com
.888.com
.tube8.com
.rapidshare8.com
.holz.byethost8.com
.jiaoyou8.com
.tt1069.com
.beijing1989.com
.waffle1999.com
.fzh999.com
.touch99.com
.buugaa.com
.kenengba.com
.new-akiba.com
.westca.com
.davidkaneda.com
.imageflea.com
.funpea.com
.k2.xrea.com
.linglingfa.com
.allinfa.com
.madebysofa.com
.idouga.com
.msguancha.com
.linksalpha.com
.allaboutalpha.com
.friendfeed-media.com
.soupofmedia.com
.highrockmedia.com
.nextmedia.com
.avwikipedia.com
.blog.jackjia.com
.zh.uncyclopedia.wikia.com
.stationeria.com
.novelasia.com
.arctosia.com
.twiyia.com
.matainja.com
.paper-replika.com
.nandalala.com
.blog.gowalla.com
.anthonycalzadilla.com
.thumbzilla.com
.nokola.com
.dupola.com
.zuola.com
.dalailama.com
.blog.taragana.com
.rfachina.com
.backchina.com
.comefromchina.com
.secretchina.com
.farwestchina.com
.chinaxchina.com
.bbs.sina.com
.dailynews.sina.com
.mizzmona.com
.blog.wakoopa.com
.zonaeuropa.com
.kechara.com
.opera.com
.my.opera.com
.wallpapercasa.com
.rapidsharedata.com
.www.6v6dota.com
.my.architexa.com
.junauza.com
.po2b.com
.plusbb.com
.imdb.com
.techlifeweb.com
.coveringweb.com
.shulib.com
.666kb.com
.www.techfob.com
.pornhub.com
.akiraclub.com
.sogclub.com
.pornstarclub.com
.www.benjamingolub.com
.yipub.com
.hk-pub.com
.foxsub.com
.forum.tvb.com
.minimalmac.com
.axureformac.com
.trulyergonomic.com
.seesmic.com
.blog.seesmic.com
.teamseesmic.com
.lookpic.com
.twitpic.com
.i28.tinypic.com
.blog.tinypic.com
.xcritic.com
.megarotic.com
.automattic.com
.hkjc.com
.graphycalc.com
.franklc.com
.dynawebinc.com
.blog.think-async.com
.toodoc.com
.docstoc.com
.hkepc.com
.global.hkepc.com
.tomsc.com
.juliereyc.com
.twit2d.com
.evhead.com
.pixelbread.com
.feeds.mobileread.com
.givemesomethingtoread.com
.tidyread.com
.sevenload.com
.megaupload.com
.multiupload.com
.slutload.com
.proxyroad.com
.typepad.com
.lawprofessors.typepad.com
.www.typepad.com
.wattpad.com
.om.shaayad.com
.scribd.com
.sandradodd.com
.qmzdd.com
.bbs.qmzdd.com
.friendfeed.com
.twitterfeed.com
.bbsfeed.com
.superspeed.com
.whatblocked.com
.www.20thingsilearned.com
.pwned.com
.2shared.com
.gutteruncensored.com
.openid.com
.demonoid.com
.pdk.android.com
.developer.android.com
.wisevid.com
.twitvid.com
.hotspotshield.com
.e-gold.com
.dalailamaworld.com
.blog.jtbworld.com
.pcworld.com
.dw-world.com
.www.mycould.com
.jayparkinsonmd.com
.bbsland.com
.goofind.com
.makemymood.com
.tripod.com
.www.tripod.com
.americangreencard.com
.tweetboard.com
.popyard.com
.hidecloud.com
.stoweboyd.com
.cynscribe.com
.kathyschwalbe.com
.hoparoundtheglobe.com
.tube.com
.redtube.com
.skimtube.com
.porntube.com
.gazotube.com
.youtube.com
.youtube\.com
.xtube.com
.sendspace.com
.squarespace.com
.telecomspace.com
.viewmorepics.myspace.com
.vids.myspace.com
.blogs.myspace.com
.cn2.streetvoice.com
.cn.streetvoice.com
.tw.streetvoice.com
.njuice.com
.thebrigade.com
.parade.com
.dongde.com
.myeclipseide.com
.xml-training-guide.com
.miroguide.com
.tweepguide.com
.rileyguide.com
.21code.com
.ihas1337code.com
.autoproxy-gfwlist.googlecode.com
.reflectivecode.com
.www.debugmode.com
.sharebee.com
.rushbee.com
.apigee.com
.ebookee.com
.blog.seeminglee.com
.somee.com
.anchorfree.com
.pioneer-worker.forums-free.com
.docs.blacktree.com
.secrets.blacktree.com
.www.blacktree.com
.metacafe.com
.cookingtothegoodlife.com
.forum.palmislife.com
.daylife.com
.duckmylife.com
.quadedge.com
.edubridge.com
.corumcollege.com
.hougaige.com
.droidie.com
.sejie.com
.youtube-nocookie.com
.abitno.linpie.com
.thetrotskymovie.com
.xiaohexie.com
.logmike.com
.onebigfluke.com
.socialwhale.com
.mashable.com
.old.nabble.com
.blog.dribbble.com
.sandnoble.com
.google.com
.picasaweb.google.com
.encrypted.google.com
.code.google.com
.knol.google.com
.video.google.com
.docs.google.com
.sites.google.com
.talkgadget.google.com
.www.google.com
.feedproxy.google.com
.socialnmobile.com
.www.stackfile.com
.chinaphile.com
.googlesile.com
.crackle.com
.c-est-simple.com
.wtfpeople.com
.helpeachpeople.com
.feeds.people.com
.powerapple.com
.chinamule.com
.cmule.com
.p2theme.com
.rssmeme.com
.tweetmeme.com
.windowsphoneme.com
.rayfme.com
.time.com
.shooshtime.com
.transparentuptime.com
.china.blogs.time.com
.geekerhome.com
.mychinamyhome.com
.downforeveryoneorjustme.com
.photos.dailyme.com
.dotplane.com
.advanscene.com
.hkheadline.com
.thedieline.com
.sokamonline.com
.meteorshowersonline.com
.blog.couchone.com
.feeds.dzone.com
.bloomfortune.com
.space-scape.com
.blog.pixelpipe.com
.skype.com
.static2.skype.com
.c.skype.com
.share.skype.com
.forum.skype.com
.login.skype.com
.go.skype.com
.shop.skype.com
.partner.skype.com
.blogs.skype.com
.support.skype.com
.movabletype.com
.pornrapidshare.com
.keepandshare.com
.smashingshare.com
.qkshare.com
.uushare.com
.feedzshare.com
.foursquare.com
.blog.foursquare.com
.topshareware.com
.igorware.com
.bill2-software.com
.ironicsoftware.com
.syniumsoftware.com
.download.syniumsoftware.com
.nurgo-software.com
.hogbaysoftware.com
.ccthere.com
.qingre.com
.throughnightsfire.com
.veempiire.com
.spankwire.com
.sproutcore.com
.vmixcore.com
.puffstore.com
.mobypicture.com
.internetpopculture.com
.7capture.com
.twibase.com
.appbase.com
.bbcchinese.com
.penchinese.com
.ozchinese.com
.bbs.ozchinese.com
.websitepulse.com
.kevinrose.com
.twitcause.com
.penthouse.com
.support.intensedebate.com
.bobulate.com
.overstimulate.com
.worstthingieverate.com
.lenwhite.com
.bkite.com
.brightkite.com
.dlsite.com
.hootsuite.com
.qanote.com
.s.evernote.com
.lyricsquote.com
.privatepaste.com
.tinypaste.com
.xinshijue.com
.randyblue.com
.fulue.com
.imagevenue.com
.thelifeyoucansave.com
.cherrysave.com
.goldwave.com
.mail-archive.com
.imlive.com
.gufeng521.spaces.live.com
.portis21.spaces.live.com
.siyi123123123.spaces.live.com
.wangyi64.spaces.live.com
.cc9007.spaces.live.com
.hujiachina.spaces.live.com
.twitese.spaces.live.com
.zhllg.spaces.live.com
.williamlong.spaces.live.com
.ieemdai.spaces.live.com
.huajiadi.spaces.live.com
.program-think.spaces.live.com
.sublexical.spaces.live.com
.zengjinyan.spaces.live.com
.yanghengjun.spaces.live.com
.wenyunchao.spaces.live.com
.chenyehao.spaces.live.com
.flowerofhappiness.spaces.live.com
.singularitys.spaces.live.com
.honeonet.spaces.live.com
.yezimary.spaces.live.com
.china-green-party.spaces.live.com
.gartlive.com
.chinainperspective.com
.summize.com
.dzze.com
.doubleaf.com
.iwfwcf.com
.purepdf.com
.drewolanoff.com
.seapuff.com
.fourwallsandaroof.com
.noypf.com
.fsurf.com
.mingpaosf.com
.mthruf.com
.chengmingmag.com
.tweepmag.com
.blog.romanandreg.com
.feeds.digg.com
.ytimg.com
.xa.yimg.com
.173ng.com
.5maodang.com
.gongminliliang.com
.fan-qiang.com
.geektang.com
.sexhuang.com
.wengewang.com
.cengkewang.com
.dongtaiwang.com
.64tianwang.com
.aboluowang.com
.ruanyifeng.com
.s1heng.com
.lidecheng.com
.slheng.com
.stuffimreading.com
.aladding.com
.myparagliding.com
.nogoodatcoding.com
.sshforwarding.com
.dongyangjing.com
.sexyandshocking.com
.fangeming.com
.tuxtraining.com
.taiwanyes.ning.com
.spencertipping.com
.caochangqing.com
.piring.com
.beijingspring.com
.fangbinxing.com
.chingcheong.com
.wefong.com
.xys.dxiong.com
.wanglixiong.com
.141hongkong.com
.am.pengyulong.com
.ch.shvoong.com
.liuxiaotong.com
.htmldog.com
.blogcatalog.com
.mynokiablog.com
.mysinablog.com
.theappleblog.com
.voachineseblog.com
.--voachineseblog.com
.aiweiweiblog.com
.dtiblog.com
.pcgeekblog.com
.triangulationblog.com
.oizoblog.com
.simpleproductivityblog.com
.thechangelog.com
.davidslog.com
.zh.netlog.com
.yfrog.com
.bloomberg.com
.urlborg.com
.melon-peach.com
.hiitch.com
.zeutch.com
.jitouch.com
.interestinglaugh.com
.ialmostlaugh.com
.veoh.com
.curvefish.com
.theblemish.com
.modfetish.com
.knowledgerush.com
.blog.path.com
.academicearth.com
.t.huhaitai.com
.ka-wai.com
.trustedbi.com
.lizhizhuangbi.com
.ranyunfei.com
.hongmeimei.com
.blog.aiweiwei.com
.dizhidizhi.com
.anobii.com
.t.jiecii.com
.hechaji.com
.hecjaji.com
.forum.mymaji.com
.couchdbwiki.com
.pbwiki.com
.theiphonewiki.com
.dailidaili.com
.omgili.com
.theatrum-belli.com
.pixelqi.com
.namsisi.com
.technorati.com
.wiki.jqueryui.com
.share.ovi.com
.wuerkaixi.com
.mayimayi.com
.yeeyi.com
.milazi.com
.muzi.com
.hkej.com
.blog.hnjhj.com
.acgkj.com
.ied2k.com
.syncback.com
.mehack.com
.www.frienddeck.com
.blog.tweetdeck.com
.fflick.com
.chrispederick.com
.blogmaverick.com
.salmiyuck.com
.ruyiseek.com
.china-week.com
.www.forum4hk.com
.ukehk.com
.blog.fizzik.com
.tibetalk.com
.flightsimtalk.com
.realraptalk.com
.tagwalk.com
.steveblank.com
.retweetrank.com
.webmink.com
.koornk.com
.cn.dayabook.com
.facebook.com
.facebook\.com
.ssbook.com
.sankaizok.com
.pk.com
.teashark.com
.6park.com
.fringenetwork.com
.plurk.com
.yzzk.com
.travelinlocal.com
.picturesocial.com
.worldjournal.com
.twitreferral.com
.samsal.com
.bnrmetal.com
.abelhadigital.com
.steverubel.com
.zannel.com
.petapixel.com
.twittermail.com
.tweetymail.com
.peacehall.com
.great-firewall.com
.hasaowall.com
.berlintwitterwall.com
.bbs.morbell.com
.ventureswell.com
.refer.ccbill.com
.video.aol.com
.aolchannels.aol.com
.about.aol.com
.etools.ncol.com
.mlcool.com
.tycool.com
.designerol.com
.vapurl.com
.michaelmarketl.com
.briefdream.com
.t.orzdream.com
.stickam.com
.www.eulam.com
.www.getyouram.com
.forum.idsam.com
.mymedia.yam.com
.blog.yam.com
.n.yam.com
.news.yam.com
.obmem.com
.jeanyim.com
.dadazim.com
.blog.palm.com
.forum.baby-kingdom.com
.steel-storm.com
.forum.cyberctm.com
.dreamaquarium.com
.wpoforum.com
.oopsforum.com
.wforum.com
.www.greenpois0n.com
.purplera1n.com
.limera1n.com
.blackra1n.com
.advertfan.com
.shinychan.com
.markmilian.com
.peeasian.com
.dumblittleman.com
.lipuman.com
.eamonnbrennan.com
.naveensrinivasan.com
.tttan.com
.tianhuayuan.com
.dajiyuan.com
.mingpaovan.com
.w.idaiwan.com
.usacn.com
.youtubecn.com
.truthcn.com
.xbookcn.com
.blog.udn.com
.bookmark.udn.com
.album.udn.com
.forum.udn.com
.dignews.udn.com
.city.udn.com
.tangben.com
.hkgolden.com
.bettween.com
.kodingen.com
.www.kodingen.com
.newchen.com
.the8pen.com
.wiredpen.com
.blog.redren.com
.blog.drakengren.com
.freemoren.com
.www.vegorpedersen.com
.blog.nicholaspatten.com
.freexinwen.com
.presentationzen.com
.value-domain.com
.36rain.com
.appbrain.com
.blog.foolsmountain.com
.blog.linkedin.com
.sharkdolphin.com
.dojin.com
.drikin.com
.hunbulin.com
.3dtin.com
.newstin.com
.blog.doughellmann.com
.cnn.com
.blogs.cnn.com
.rss.cnn.com
.twibbon.com
.echofon.com
.avoision.com
.fringetelevision.com
.sexandsubmission.com
.sharepointeducation.com
.stickeraction.com
.interfaceaddiction.com
.gopetition.com
.dailymotion.com
.mathiew-badimon.com
.palacemoon.com
.brandonhutchinson.com
.getiton.com
.glennhilton.com
.calebelston.com
.zaozon.com
.eevpn.com
.jyzj.waqn.com
.wearn.com
.porn.com
.megaporn.com
.art-or-porn.com
.youporn.com
.nesn.com
.twitonmsn.com
.liudejun.com
.songjianjun.com
.chn.chosun.com
.boxun.com
.pidown.com
.lockdown.com
.yvesgeleyn.com
.pinoy-n.com
.cctongbao.com
.youthbao.com
.renminbao.com
.jieshibaobao.com
.zaobao.com
.luntan.zaobao.com
.faydao.com
.freegao.com
.wenyunchao.com
.meirixiaochao.com
.isaacmao.com
.robertmao.com
.mingpao.com
.nysingtao.com
.bebo.com
.cyberghost.natado.com
.tagxedo.com
.nakido.com
.roodo.com
.megavideo.com
.googlevideo.com
.livevideo.com
.calameo.com
.cn.calameo.com
.vimeo.com
.truveo.com
.allinfo.com
.sharpinsandiego.com
.diigo.com
.oursogo.com
.fftogo.com
.writer.zoho.com
.smedio.com
.yidio.com
.bralio.com
.contests.twilio.com
.pullfolio.com
.panoramio.com
.corywatilo.com
.vidoemo.com
.videomo.com
.twitgoo.com
.hk.rd.yahoo.com
.hk.knowledge.yahoo.com
.meme.yahoo.com
.upcoming.yahoo.com
.hk.myblog.yahoo.com
.tw.myblog.yahoo.com
.hk.search.yahoo.com
.hk.yahoo.com
.video.yahoo.com
.--video.yahoo.com
.hk.news.yahoo.com
.tw.news.yahoo.com
.tw.yahoo.com
.c1522.mooo.com
.fooooo.com
.vaayoo.com
.nuexpo.com
.pingmicro.com
.mixero.com
.en.tuxero.com
.techparaiso.com
.turningtorso.com
.getjetso.com
.blog.hotpotato.com
.thkphoto.com
.tweetphoto.com
.freelotto.com
.ueuo.com
.kanzhongguo.com
.conoyo.com
.starp2p.com
.moviefap.com
.wiki.phonegap.com
.entermap.com
.twitzap.com
.bugbeep.com
.shaunthesheep.com
.changp.com
.picturedip.com
.no-ip.com
.mimivip.com
.vanilla-jp.com
.get-digital-help.com
.beta.usejump.com
.funp.com
.gimpshop.com
.fourface.nodesnoop.com
.bitsnoop.com
.holykaw.alltop.com
.getcloudapp.com
.speckleapp.com
.blog.birdhouseapp.com
.simplenoteapp.com
.snippetsapp.com
.gabocorp.com
.tweetbackup.com
.meetup.com
.twazzup.com
.wp.com
.twitiq.com
.4sq.com
.ipobar.com
.slashgear.com
.talbenshahar.com
.tor.updatestar.com
.roteiro.geedr.com
.boardreader.com
.zhreader.com
.tvider.com
.coolder.com
.adultfriendfinder.com
.collateralmurder.com
.feer.com
.ezpeer.com
.helloqueer.com
.blogger.com
.twblogger.com
.bullogger.com
.twitlonger.com
.kurtmunger.com
.icanhascheezburger.com
.feministteacher.com
.tumblr.awflasher.com
.gather.com
.twitgether.com
.dotheyfolloweachother.com
.waiwaier.com
.youmaker.com
.gseeker.com
.pacificpoker.com
.feeds.gawker.com
.coolaler.com
.www.dwheeler.com
.newsminer.com
.i2runner.com
.buddyrunner.com
.wordboner.com
.makeyourownwordboner.com
.github.danmarner.com
.blog.danmarner.com
.whereiswerner.com
.feeds2.feedburner.com
.feeds.feedburner.com
.blog.instapaper.com
.twapperkeeper.com
.woeser.com
.the-bowser.com
.boltbrowser.com
.qtweeter.com
.ronjoneswriter.com
.sshcenter.com
.blog.wundercounter.com
.twittercounter.com
.blog.kickstarter.com
.hkreporter.com
.xhamster.com
.togetter.com
.twitter.com
.twitter\.com
.turbotwitter.com
.status.twitter.com
.herbsutter.com
.revver.com
.power.com
.tomatovpn.keithmoyer.com
.www.keithmoyer.com
.anonymizer.com
.toutfr.com
.betfair.com
.opnir.com
.alkasir.com
.flickr.com
.twitterkr.com
.twtkr.com
.tumblr.com
.media.tumblr.com
.data.tumblr.com
.static.tumblr.com
.blog.opentumblr.com
.assets.tumblr.com
.ifanr.com
.siteadvisor.com
.bbs.1tor.com
.mingpaotor.com
.wormsculptor.com
.twttr.com
.getfreedur.com
.skydur.com
.feeds.loiclemeur.com
.www.loiclemeur.com
.blog.pikchur.com
.billywr.com
.www.modernizr.com
.petardas.com
.wahas.com
.zarias.com
.blog.thinglabs.com
.1984bbs.com
.99bbs.com
.www.orchidbbs.com
.buffalo-bbs.com
.mitbbs.com
.yilubbs.com
.taiwannation.50webs.com
.freewebs.com
.twibs.com
.verybs.com
.snsanalystics.com
.goodreads.com
.www.ajsands.com
.newgrounds.com
.proboards.com
.www.proboards.com
.dajusha.baywords.com
.wordsandturds.com
.shapeservices.com
.thehungrydudes.com
.sobees.com
.anti.anti.cnn.googlepages.com
.myboooks.googlepages.com
.freegateget.googlepages.com
.chrome.plantsvszombies.com
.jgoodies.com
.geocities.com
.hk.geocities.com
.xmovies.com
.ladbrokes.com
.bonersgames.com
.wetpussygames.com
.latimesblogs.latimes.com
.camera.chinatimes.com
.gb.chinatimes.com
.blog.chinatimes.com
.forum.chinatimes.com
.news.chinatimes.com
.tweetedtimes.com
.epochtimes.com
.duoweitimes.com
.bloglines.com
.kcsoftwares.com
.blog.expofutures.com
.plurktemplates.com
.pmates.com
.thegatesnotes.com
.madmenfootnotes.com
.wiredbytes.com
.gqueues.com
.masamixes.com
.cn.news.cnyes.com
.networkedblogs.com
.rconversation.blogs.com
.9bis.com
.soft-artemis.com
.www.socialwhois.com
.generesis.com
.ngensis.com
.blog.dustincurtis.com
.mpettis.com
.iphonehacks.com
.gtricks.com
.www.dropmocks.com
.www.html5rocks.com
.apirocks.com
.bonjourlesgeeks.com
.mirrorbooks.com
.pbworks.com
.gardennetworks.com
.tvunetworks.com
.aurorasoftworks.com
.geekmanuals.com
.littlebigdetails.com
.pdetails.com
.geometrictools.com
.alternate-tools.com
.tzangms.com
.sorting-algorithms.com
.bolin.netfirms.com
.gtkforums.com
.keyfans.com
.tweetrans.com
.willhains.com
.tkcs-collins.com
.www.liteapplications.com
.threatchaos.com
.xvideos.com
.qoos.com
.tv-intros.com
.rawfoodsos.com
.chinatweeps.com
.tek-tips.com
.semicolonapps.com
.pokerstars.com
.aenhancers.com
.goodreaders.com
.navigeaters.com
.feeds.reuters.com
.firstfivefollowers.com
.edoors.com
.whippedass.com
.blog.lastpass.com
.hidemyass.com
.video.foxbusiness.com
.wordpress.com
.caiting666.wordpress.com
.rfaunplugged.wordpress.com
.zhenxiang.wordpress.com
.zh-sg.wordpress.com
.zh-cn.wordpress.com
.files.wordpress.com
.cafepress.com
.taiwankiss.com
.elisabethkublerross.com
.page2rss.com
.pcdiscuss.com
.heungkongdiscuss.com
.gs-discuss.com
.omg-facts.com
.breakingtweets.com
.news.atebits.com
.sinoants.com
.uwants.com
.chromeexperiments.com
.nowtorrents.com
.searchfreefonts.com
.webshots.com
.designers-artists.com
.photofocus.com
.blog.headius.com
.primedius.com
.delicious.com
.blog.obvious.com
.posterous.com
.rayous.com
.qstatus.com
.voanews.com
.latelinenews.com
.freemorenews.com
.mpinews.com
.etaiwannews.com
.astonmartinnews.com
.mingpaonews.com
.so-news.com
.feeds.cbsnews.com
.app.hkatvnews.com
.dwnews.com
.nownews.com
.blog.nownews.com
.forum.nownews.com
.newcenturynews.com
.blog.growlforwindows.com
.ultraxs.com
.plurktop-button.mmdays.com
.plurktop.mmdays.com
.navicat.com
.thisiswhyyouarefat.com
.whydidyoubuymethat.com
.wattsupwiththat.com
.twitthat.com
.twitstat.com
.retweeteffect.com
.www.googleartproject.com
.12bet.com
.tibet.com
.canadameet.com
.t.jteet.com
.splitweet.com
.buzzcantweet.com
.mrtweet.com
.chinese.engadget.com
.twittergadget.com
.blogs.icerocket.com
.ironhelmet.com
.myfreshnet.com
.chinesenewsnet.com
.slinkset.com
.slavasoft.com
.efksoft.com
.eriversoft.com
.unholyknight.com
.bbs.allhabit.com
.blog.reddit.com
.yousendit.com
.blog.typekit.com
.wiki.js-kit.com
.blog.metasploit.com
.pornvisit.com
.moblog.bradleyit.com
.heartyit.com
.postadult.com
.askstudent.com
.blog.bittorrent.com
.webcache.googleusercontent.com
.blog.pathtosharepoint.com
.isohunt.com
.fleshbot.com
.mademoisellerobot.com
.geohot.com
.tokyo-hot.com
.amiblockedornot.com
.blogspot.com
.thevivekspot.com
.appspot.com
.meme2028.appspot.com
.go2china8.appspot.com
.squall0629.appspot.com
.twitese.appspot.com
.waterzeong.appspot.com
.bullog4cn.appspot.com
.twitter-mirror.appspot.com
.twittergadget.appspot.com
.chnshot.appspot.com
.nest.appspot.com
.proxypy.appspot.com
.www.romeo-foxtrot.com
.blog.jsquaredjavascript.com
.r-chart.com
.www.chinesealbumart.com
.bbs.ecstart.com
.twivert.com
.mytwishirt.com
.myaudiocast.com
.sopcast.com
.amoiist.com
.thesartorialist.com
.retweetist.com
.marxist.com
.kinghost.com
.atlaspost.com
.thetibetpost.com
.alabout.com
.atnext.com
.hellotxt.com
.martau.com
.waigaobu.com
.ziddu.com
.fengzhenghu.com
.liujianshu.com
.sexhu.com
.laomiu.com
.twitter.missiu.com
.muouju.com
.tsemtulku.com
.wenku.com
.heroku.com
.lalulalu.com
.hulu.com
.yy.iyatou.com
.karayou.com
.zhinengluyou.com
.wowubuntu.com
.galenwu.com
.92ccav.com
.eic-av.com
.epc-jav.com
.thisav.com
.vinniev.com
.imkev.com
.analyze-v.com
.ntdtv.com
.oiktv.com
.ippotv.com
.limesn0w.com
.legaltech.law.com
.rss.berryreview.com
.higfw.com
.fuckgfw.com
.aboutgfw.com
.rlwlw.com
.twisternow.com
.tvboxnow.com
.mesotw.com
.x365x.com
.x1949x.com
.city9x.com
.xxbbx.com
.sex.com
.aisex.com
.taiwan-sex.com
.robtex.com
.tnaflix.com
.blog.netflix.com
.placemix.com
.blinkx.com
.ginx.com
.theultralinx.com
.noobbox.com
.video.fdbox.com
.www.wavesandbox.com
.dropbox.com
.xvediox.com
.sweux.com
.mmaaxx.com
.twindexx.com
.mixx.com
.t66y.com
.blogs.tampabay.com
.a-normal-day.com
.blog.louisgray.com
.chaos.e-spacy.com
.blog.polldaddy.com
.christianstudy.com
.ydy.com
.robustnessiskey.com
.blog.tiney.com
.gclooney.com
.eltondisney.com
.sippey.com
.blog.topify.com
.zh.pokerstrategy.com
.blog.feedly.com
.mingpaomonthly.com
.webworkerdaily.com
.tweetwally.com
.philly.com
.multiply.com
.twitturly.com
.brizzly.com
.sexyandfunny.com
.mingpaony.com
.netcolony.com
.eyny.com
.www.voy.com
.proxypy.com
.podictionary.com
.news.ghostery.com
.illusionfactory.com
.tistory.com
.topsy.com
.homepage2.nifty.com
.wenxuecity.com
.kusocity.com
.droidsecurity.com
.thesponty.com
.chinasocialdemocraticparty.com
.jimoparty.com
.lrfz.com
.315lz.com
.bhorowitz.com
.youjizz.com
.blog.syx86.cn
.memedia.cn
.daxa.cn
.gmbd.cn
.t.neolee.cn
.google.cn
.roosong.cn
.businesstimes.com.cn
.aidsmuseum.cn
.sjum.cn
.xh4n.cn
.po.inewton.cn
.log.keso.cn
.wiki.keso.cn
.my.keso.cn
.t.16class.cn
.log.thws.cn
.zhongxing9hao.net.cn
.qixianglu.cn
.vanemu.cn
.onlylady.cn
.li2z.cn
.bbc.in
.s.xiaod.in
.tuite.in
.benjaminste.in
.teck.in
.topnews.in
.css.pixnet.in
.photou.in
.t.co
.module.do
.blog.nicovideo
.ngs2.info
.say2.info
.909090909.info
.uncyclopedia.info
.hjclub.info
.gzone-anime.info
.blog.istef.info
.weekmag.info
.twreg.info
.2008xianzhang.info
.gongmeng.info
.kzeng.info
.blog.lidaobing.info
.theqii.info
.bbs.tuitui.info
.dy24k.info
.everdark.info
.blog.kowalczyk.info
.caobian.info
.proxomitron.info
.free-vpn.info
.taolun.info
.t.sunxun.info
.cellulo.info
.soumo.info
.stoneip.info
.chinaworker.info
.ajaxplorer.info
.wikilivres.info
.winwhispers.info
.eyespirit.info
.blog.persistent.info
.one.xthost.info
.sinopitt.info
.upload4u.info
.blog.liukangxu.info
.blog.youxu.info
.suicideblitz.info
.twaud.io
.blog.couch.io
.soup.io
.static.soup.io
.blog.boxcar.io
.wikimedia.org.mo
.nrk.no
.secretgarden.no
.tora.to
.mash.to
.siteks.uk.to
.destiny.xfiles.to
.us.to
.bbs.mychat.to
.4.gp
.30.php
.121822.php
.china.php
.viewthread.php
.page.php
.login.php
.index.php
.woopie.jp
.graphis.ne.jp
.asdfg.jp
.blogimg.jp
.exblog.jp
.www.exblog.jp
.wikiwiki.jp
.buzzurl.jp
.orn.jp
.sod.co.jp
.blog.exblog.co.jp
.geocities.co.jp
.nicovideo.jp
.--tw.nicovideo.jp
.twitter.jp
.geocities.jp
.nexton-net.jp
.baidu.jp
.dl-laby.jp
.x.xcity.jp
.isbnInquiry.asp
.docDetail.jsp
.365singles.com.ar
.antidrm.hpg.ig.com.br
.-------------Google.other-----
.free.fr
.dimitrik.free.fr
.puttycm.free.fr
.kineox.free.fr
.allonlinux.free.fr
.flecheinthepeche.fr
.rfi.fr
.ultravpn.fr
.ultrevpn.fr
.iphonix.fr
.incredibox.fr
.start.cs
.twittertim.es
.wofa.us
.paperb.us
.dit-inc.us
.foxdie.us
.livingonline.us
.topshare.us
.sitetag.us
.zyzg.us
.freessh.us
.imageshack.us
.hellonewyork.us
.photo.utom.us
.guomin.us
.izaobao.us
.dontfilter.us
.oasisnewsroom.live4ever.us
.geohot.us
.thedw.us
.cgiproxy.us
.1free.ws
.blog.agile.ws
.thedailywh.at
.blog.go2web20.net
.junefourth-20.net
.site90.net
.yx51.net
.6-4.net
.sysadmin1138.net
.qusi8.net
.tt1069.net
.fzh999.net
.so-ga.net
.nekoslovakia.net
.drivingitalia.net
.witopia.net
.dupola.net
.danke4china.net
.observechina.net
.greatfirewallofchina.net
.prayforchina.net
.nc.alwaysdata.net
.minzhuhua.net
.shell.cjb.net
.hdtvb.net
.blog.pentalogic.net
.fuckcnnic.net
.tor.blingblingsquad.net
.bloodshed.net
.gun-world.net
.totalcmd.net
.e-traderland.net
.flickrhivemind.net
.blogtd.net
.picidae.net
.sourceforge.net
.wujie.net
.ulike.net
.cocoa.zonble.net
.zoozle.net
.sneakme.net
.mclee.foolme.net
.hackthatphone.net
.seezone.net
.wezone.net
.blog.bcchinese.net
.penchinese.net
.zhonggtuotese.net
.wanderinghorse.net
.www.metamuse.net
.tweete.net
.m.tweete.net
.blog.xuite.net
.vlog.xuite.net
.twitter.fishnote.net
.t.fishnote.net
.lianyue.net
.chinainperspective.net
.sesawe.net
.iblogserv-f.net
.jyxf.net
.webbang.net
.tuidang.net
.dongtaiwang.net
.liaowangxizang.net
.washeng.net
.xinsheng.net
.stuffimreading.net
.yuanming.net
.gaoming.net
.feeds.boingboing.net
.cuiweiping.net
.duping.net
.huping.net
.sunjidong.net
.xuzhiyong.net
.shifeike.blog125.fc2blog.net
.classicalguitarblog.net
.prasannatech.net
.new-3lunch.net
.blog.hexxeh.net
.wiki.oauth.net
.wlx.sowiki.net
.apps.hloli.net
.feeds.limi.net
.gaopi.net
.wangruoshui.net
.wukangrui.net
.fanqiangyakexi.net
.tsong.yunxi.net
.chuizi.net
.muzi.net
.rxhj.net
.ied2k.net
.chrispederick.net
.mobatek.net
.inmediahk.net
.www.kyohk.net
.naitik.net
.ismprofessional.net
.frommel.net
.crossthewall.net
.clientsfromhell.net
.furl.net
.your-freedom.net
.jkforum.net
.lsforum.net
.michaeldehaan.net
.caodan.net
.daolan.net
.panluan.net
.ac.jiruan.net
.tonyyan.net
.pign.net
.zhanbin.net
.sethwklein.net
.ironpython.net
.romnation.net
.verizon.net
.caterpillar.onlyfun.net
.yunchao.net
.usbloadergx.koureio.net
.maiio.net
.tcno.net
.weeewooo.net
.derekhsu.homeip.net
.hsjp.net
.delcamp.net
.fotop.net
.letscorp.net
.twstar.net
.m.slandr.net
.exploader.net
.linux-engineer.net
.blog.davidziegler.net
.gmer.net
.twitbrowser.net
.en.favotter.net
.kompozer.net
.wiki.addonsmirror.net
.forum.addonsmirror.net
.szbbs.net
.popularpages.net
.izles.net
.stonegames.net
.chinadigitaltimes.net
.sytes.net
.s.pixfs.net
.9bis.net
.stoptibetcrisis.net
.chinesetalks.net
.swift-tools.net
.kendincos.net
.creaders.net
.pocketmonsters.net
.erights.net
.uwants.net
.pureconcepts.net
.old-cat.net
.gdbt.net
.web2project.net
.tibet.net
.itweet.net
.blog.tsunanet.net
.times.hinet.net
.pixnet.net
.megabyet.net
.lich355.megabyet.net
.ytht.net
.hkg.westkit.net
.chinese-hermit.net
.ignitedetroit.net
.paint.net
.blog.joint.net
.blog.notdot.net
.www.greasespot.net
.geek-art.net
.marxist.net
.wangafu.net
.sapikachu.net
.zuihulu.net
.hecaitou.net
.webs-tv.net
.willw.net
.jonny.ubuntu-tw.net
.sexinsex.net
.developers.box.net
.s3fox.net
.flagfox.net
.nemesis2.qx.net
.hkday.net
.middle-way.net
.blog.umonkey.net
.taiwandaily.net
.longtermly.net
.proxypy.net
.log.lightory.net
.twistory.net
.cl.d0z.net
.uighurbiz.net
.askynz.net
.prozz.net
.video.tiscali.it
.www.modk.it
.asianews.it
.htxt.it
.china.ArticleList.ArticleList
.nf.id.au
.tp.vbap.com.au
.xxxx.com.au
.www.radioaustralia.net.au
.humanities.uchicago.edu
.emory.edu
.qtrac.eu
.cenews.eu
.hugoroy.eu
.yong.hu
.liu.lu
.bot.nu
.ipicture.ru
.webfee.org.ru
.portablesoft.org.ru
.xzy.org.ru
.a5.com.ru
.gigporno.ru
.top1.pp.ru
.abc.pp.ru
.bill.zhong.pp.ru
.xfm.pp.ru
.heix.pp.ru
.samair.ru
.net.ru
.cecc.gov
.usinfo.state.gov
.bbg.gov
.earthquake.usgs.gov
.nps.gov
.tibetonline.tv
.tsquare.tv
.ustream.tv
.im.tv
.myvlog.im.tv
.gzm.tv
.boxun.tv
.truth101.co.tv
.1pondo.tv
.jobso.tv
.blip.tv
.domain.club.tw
.inote.tw
.coolloud.org.tw
.kagyuoffice.org.tw
.nccwatch.org.tw
.wufi.org.tw
.rti.org.tw
.atj.org.tw
.e-info.org.tw
.dpp.org.tw
.web.pts.org.tw
.news.pts.org.tw
.talk.news.pts.org.tw
.tibet.org.tw
.ait.org.tw
.taiwantt.org.tw
.hakkatv.org.tw
.greenparty.org.tw
.newtalk.tw
.findbook.tw
.cna.com.tw
.blog.sina.com.tw
.magazines.sina.com.tw
.books.sina.com.tw
.news.sina.com.tw
.cnavista.com.tw
.bcc.com.tw
.khmusic.com.tw
.1-apple.com.tw
.forum.slime.com.tw
.forum.pchome.com.tw
.mypaper.pchome.com.tw
.news.pchome.com.tw
.kingstone.com.tw
.gamebase.com.tw
.a.rimg.com.tw
.b.rimg.com.tw
.c.rimg.com.tw
.nch.com.tw
.myshare.url.com.tw
.ruten.com.tw
.sanmin.com.tw
.news.msn.com.tw
.buy.yahoo.com.tw
.gamer.com.tw
.readingtimes.com.tw
.libertytimes.com.tw
.oikos.com.tw
.backpackers.com.tw
.cdnews.com.tw
.plays.com.tw
.zdnet.com.tw
.beta.iset.com.tw
.forum.iset.com.tw
.vft.com.tw
.topic.youthwant.com.tw
.share.youthwant.com.tw
.blog.youthwant.com.tw
.bb.ttv.com.tw
.nexttv.com.tw
.forum.setty.com.tw
.gamez.com.tw
.blog.kengao.tw
.nicovideo.tw
.sitebro.tw
.twbbs.net.tw
.student.tw
.cdp.sinica.edu.tw
.bbs.nsysu.edu.tw
.cbs.ntu.edu.tw
.idv.tw
.gov.tw
.921.gov.tw
.nmmba.gov.tw
.klra.gov.tw
.klccab.gov.tw
.cycab.gov.tw
.tchb.gov.tw
.grb.gov.tw
.cwb.gov.tw
.tcsac.gov.tw
.chccc.gov.tw
.hcc.gov.tw
.hchcc.gov.tw
.khcc.gov.tw
.tphcc.gov.tw
.hsinchu-cc.gov.tw
.aec.gov.tw
.tncsec.gov.tw
.ntsec.gov.tw
.4pppc.gov.tw
.itrc.gov.tw
.vghtc.gov.tw
.thbstc.gov.tw
.nmvttc.gov.tw
.yvtc.gov.tw
.gysd.nyc.gov.tw
.womenbusiness.nyc.gov.tw
.aide.gov.tw
.tpde.aide.gov.tw
.ncree.gov.tw
.stdtime.gov.tw
.moe.gov.tw
.vghtpe.gov.tw
.taitung-house.gov.tw
.cp-house.gov.tw
.dapu-house.gov.tw
.arte.gov.tw
.df.gov.tw
.stag.gov.tw
.wanfang.gov.tw
.chukuang.gov.tw
.etraining.gov.tw
.nerch.gov.tw
.kmseh.gov.tw
.aftygh.gov.tw
.ntdmh.gov.tw
.kmh.gov.tw
.nmh.gov.tw
.ntuh.gov.tw
.nhri.gov.tw
.nvri.gov.tw
.kk.gov.tw
.nerhl.gov.tw
.nmtl.gov.tw
.ntl.gov.tw
.npm.gov.tw
.nstm.gov.tw
.taoyuan.gov.tw
.yatsen.gov.tw
.hengchuen.gov.tw
.imagesblog.gio.gov.tw
.comnews.gio.gov.tw
.klsio.gov.tw
.nspo.gov.tw
.pabp.gov.tw
.dmtip.gov.tw
.nmp.gov.tw
.ner.gov.tw
.iner.gov.tw
.bdhr.gov.tw
.patehr.gov.tw
.lungtanhr.gov.tw
.mvdis.gov.tw
.vghks.gov.tw
.khms.gov.tw
.matsu-news.gov.tw
.cromotc.nat.gov.tw
.nici.nat.gov.tw
.ncdr.nat.gov.tw
.gsn-cert.nat.gov.tw
.tax.nat.gov.tw
.nict.gov.tw
.pet.gov.tw
.president.gov.tw
.nertt.gov.tw
.0rz.tw
.ArtShow.aspx
.img.ly
.cl.ly
.f.cl.ly
.w.sns.ly
.ht.ly
.blog.bit.ly
.post.ly
.ow.ly
.uniteddaily.com.my
.static.py
.request.py
.jiehua.cz
.tweetboner.biz
.4bluestones.biz
.nzchinese.net.nz
