#!/bin/bash
echo '{+forward-override{forward-socks4a 127.0.0.1:9050 .}}'>gfwlist.action
<gfwlist grep -o -E '([\.[[:alnum:]\-])+'|sed -re's/^\.//'|grep -E '\.[[:alnum:]]'|rev|sort -u|rev|awk '{if (!/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/) {printf(".") }}{print $0}'>>gfwlist.action
